# Generated by Django 6.0.7 on 2026-07-16 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='player',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='tournament',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
        migrations.DeleteModel(
            name='Tournament',
        ),
    ]
